services:
  - type: web
    name: hirepro-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PGUSER
        value: postgres
      - key: PGPASSWORD
        value: ugSYeuYDVcQariTdoRXsHBJaOumcgauX
      - key: PGHOST
        value: trolley.proxy.rlwy.net
      - key: PGDATABASE
        value: railway
      - key: PGPORT
        value: "40947"

  - type: cron
    name: hirepro-scraper
    env: python
    schedule: "0 */6 * * *"  # Run every 6 hours
    buildCommand: pip install -r requirements.txt
    startCommand: python scraper.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PGUSER
        value: postgres
      - key: PGPASSWORD
        value: ugSYeuYDVcQariTdoRXsHBJaOumcgauX
      - key: PGHOST
        value: trolley.proxy.rlwy.net
      - key: PGDATABASE
        value: railway
      - key: PGPORT
        value: "40947" 